// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1NYpvKa6JOJWeg4yYKhNNWbVPy-pQ45M',
    appId: '1:513017338219:web:ade78670e8be38bd42942e',
    messagingSenderId: '513017338219',
    projectId: 'pothole-mobile-app',
    authDomain: 'pothole-mobile-app.firebaseapp.com',
    storageBucket: 'pothole-mobile-app.firebasestorage.app',
    measurementId: 'G-ML1M0Z992E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ZnnYIKUpufZtDYFuGV7DWT_Gnwty-g8',
    appId: '1:513017338219:android:f75e8e3e6e047cf042942e',
    messagingSenderId: '513017338219',
    projectId: 'pothole-mobile-app',
    storageBucket: 'pothole-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxMkYRk5AP5AQqK7xBe4E4xBTAfuaoVk',
    appId: '1:513017338219:ios:f8a45f24de817cf042942e',
    messagingSenderId: '513017338219',
    projectId: 'pothole-mobile-app',
    storageBucket: 'pothole-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.potholeMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxMkYRk5AP5AQqK7xBe4E4xBTAfuaoVk',
    appId: '1:513017338219:ios:f8a45f24de817cf042942e',
    messagingSenderId: '513017338219',
    projectId: 'pothole-mobile-app',
    storageBucket: 'pothole-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.potholeMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1NYpvKa6JOJWeg4yYKhNNWbVPy-pQ45M',
    appId: '1:513017338219:web:527fb0de0b9bc31542942e',
    messagingSenderId: '513017338219',
    projectId: 'pothole-mobile-app',
    authDomain: 'pothole-mobile-app.firebaseapp.com',
    storageBucket: 'pothole-mobile-app.firebasestorage.app',
    measurementId: 'G-0HWSDZDVHL',
  );
}
